version: "3.7"

services:
  builder:
    image: whereqr-front
    build:
      context: builder/
      dockerfile: Dockerfile
    volumes:
      - "./src:/builder/src"
    working_dir: /builder

  runner:
    image: nginx:latest
    volumes:
      - "./build:/app/build"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
